services:
  backend:
    image: wardrowbe/backend:main-local
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    image: wardrowbe/frontend:main-local
    build:
      context: ./frontend
      dockerfile: Dockerfile

  worker:
    image: wardrowbe/backend:main-local
    build:
      context: ./backend
      dockerfile: Dockerfile
